---
# tasks file for kafka

- block:
  - name: download kafka
    unarchive:
      src: "{{ kafka_url }}"
      dest: /opt
      copy: no
      creates: "{{ kafka_dest }}"
      owner: root
      group: root

  - name: link the preferred kafka version
    file:
      path: "{{ kafka_prefix }}/kafka"
      src: "{{ kafka_dest }}"
      state: link

  - name: kafka server config
    template:
      dest: "{{ kafka_dest }}/config/server.properties"
      src: "server-{{ kafka_main_ver }}.properties.j2"
      owner: root
      group: root
      mode:  0644

  become: true
  become_method: sudo
  tags:
    - kafka
